name: Main workflow

on:
  push:
    branches:
      - dev
      - qual
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build .NET Core
      run: dotnet build --configuration Release
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Run tests (target framework netcoreapp3.1)
      run: dotnet test ./YetiApi.sln --configuration Release --framework netcoreapp3.1 --list-tests
